### ISSUE TITLE
I think this breaks the rules of graphs

### ISSUE THREAD

**Issue by lxcyp** [antoligy/healthbeacon#1]
When going between Home and Dashboard, and extra loop is added to the graph. 
![160503-nubrc](https://cloud.githubusercontent.com/assets/5414038/14981240/aaf0267a-1125-11e6-8ba9-e2d3b27db55f.png)

**Comment by alexwilson** [comment]
Cheers for reporting!

Yes this is probably because right now the FitnessStore re-fetches the entire set of data-points when you view the page.  Should be a quick fix, I'm planning on porting this all to Redux anyway.

**Comment by alexwilson** [comment]
Hey,  this should have been fixed in 251abb25ed3334c4032dbdf2a9ad1a02cac8fd54.  Would you mind taking another look?

**Comment by lxcyp** [comment]
can confirm, it's fixed! closing issue.
